apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.70
  share: /data_k8s
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
